<?php /* tos.php */ ?>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title><?php echo $sb['sb_name']; ?> Spin-O-Rama</title>
	<link rel="stylesheet" type="text/css" media="screen" href="styles/spin-o-rama.css" />
</head>
<body>
	<div id="container">
		<section class="winner-form">
			The following Terms and Conditions apply to "Spin-O-Rama" ("The Competition") and by participating in the competition, you are deemed to have read, understood, and accepted the same. Please read these Terms and Conditions carefully before deciding to participate in the competition.
			1. Competition's Theme: The contestants participating in the competition will click on a lever with the aim of aligning the icons as designated on the game itself. Spin-O-Rama is a simple game that you can win with a 'click of the mouse'. There prizes up for grabs every Tuesday ONLY between 9-10AM: You can only play 1 time in every Tuesday. Winners &amp; prizes are at complete random &amp; it is possible to win the same prize each Tuesday that you play. The Grand Prizes that can be won are trips to Aruba, Orlando &amp; Las Vegas. Trips are subject to availability and cannot be redeemed for cash or reimbursed if the winner misses their trip on the days they selected to take.
			2. Competition Period and Eligibility: (a) To participate in the Competition you must be over 18 years of age (as at the date of entry), have a valid email address, and if the winner wins a gift card -a valid mailing address must be submitted. By entering the competition, you are agreeing to be bound by these Terms and Conditions. In addition, you are representing that the details provided are true and complete, including that your personal details are true. (Name, Email, Address.) (b) The competition is ONLY valid every Tuesday from 9-10AM. ("Competition Period")
			3. Entry into the Competition: (i) Each and every Tuesday beginning at 9AM and ending at 10AM, a link to the game will be provided on the following websites &amp; Facebook PAGES: Bonnie &amp; Clyde's Restaurant, North Park Lounge Cranberry, North Park Lounge McCandless, Bamboo Bar &amp; Cabana Bar. (iii) Contestants will have the opportunity to "Share" the game and/or what they've won (If winner) to their personal Facebook Pages.
			4. Selection of Winners (a) The lucky winners with the specific icon alignment (shown on game) will win the prize shown. (b) Each contestant can play only 1 time every Tuesday from 9-10AM. (c) If one does not submit their details right after winning a prize, the prize will be null and void. (d)It is the responsibility of the winner to provide their correct contact details for their prize. (Name, Email, Address)
			5. Winner Notification: The Winner's prize will be sent directly to their provided email address upon winning. Each prize with the exception of gift cards &amp; grand prize "trips" have a 90 day expiration date from the date they play the game. If a player wins a gift card, the gift card will be mailed to their provided address within 7-10 business days-notification of winning gift card be sent to provided email address.
			7. Other Terms (a) The winners shall redeem their prize at ONLY at the restaurant that is shown, and shall accept the prize as it is. Prizes are not redeemable for cash and are not valid with any other offer, deal or prize. (b) All prizes are non-transferrable and winners must show proof of ID to claim. (c) All prizes not redeemed after 90 days of winning date shall be forfeited. (d) By entering the competition you: i. agree that Spin-O-Rama and its participating restaurant locations and its agents are not responsible for any misuse of the prizes won. ii. agree that all prizes won MUST redeemed within the designated 90 day expiration date iii. agree that you will NOT try to re-produce, re-use or transfer any prizes won and you will provide proper identification when redeeming prizes. (e) All promotional images produced by Spin-O-Rama associated with the competition, contestants, winners, and prizes will be the property of Spin-O-Rama and its restaurant entities and may be used on the site. (f) agree that any and all personal information/data relating to you collected by Spin-O-Rama from the Site from time to time may be used and disclosed for purposes relating to the competition and to such persons as may be involved in operating or promoting the competition. (g) To the extent permitted by applicable law, you agree that Spin-O-Rama &amp; its 
			restaurant owners, locations and employees will not be liable, under any circumstances and in any way, for any errors or omissions, loss or damage of any kind incurred as a result of your use of the site, participation in the competition, or any content posted on the site. To the extent that Spin-O-Rama &amp; its restaurant owners, locations and employees suffers any claim, loss, damage or judgment due to your acts or omissions (including, but not limited to, content you post on the Site and your participation in the Competition) you agree to indemnify and hold harmless Spin-O-Rama &amp; its restaurant owners, locations and employees and its respective officers. (h) If you are in breach of any of these Terms and Conditions Spin-O-Rama &amp; its restaurant owners, locations and employees may immediately withdraw your participation &amp; winnings in the Competition without notice. (i) Spin-O-Rama &amp; its restaurant owners, locations and employees reserves the right to cancel the Competition at any time if it feels it appropriate to do so due to technical, unauthorized human intervention or any other reason. Spin-O-Rama &amp; its restaurant owners, locations and employees may change any dates set for the Competition at its absolute discretion by posting any new dates on the Site or otherwise notifying the relevant participants. (j) You acknowledge that the competition is in no way sponsored, endorsed or administered by, or associated with, Facebook and all personal information/data provided by you on the site is to Spin-O-Rama &amp; its restaurant owners, locations and employees and not to Facebook. To the extent permitted by applicable law, you agree that Facebook will not be liable, under any circumstances and in any way, for any errors or omissions, loss or damage of any kind incurred as a result of your use of the site, participation in the competition or any content posted on the site
		</section>
	</div>
</body>
</html>